### ISSUE TITLE
Creating a gzipped tar package of a large file fails

### ISSUE THREAD

**Issue by emetsger** [DataConservancy/dcs-packaging-tool#35]
Attempting to create a package with a 35GiB file fails when choosing the `tar` and `gzip` packaging options:

<img width="797" alt="screen shot 2017-04-10 at 11 55 39 am" src="https://cloud.githubusercontent.com/assets/146970/24870597/d66efc32-1de4-11e7-9a84-67b47afd96a4.png">

**Comment by emetsger** [comment]
In addition, no errors were seen in the console (when launched via `mvn jfx:run`); I would have expected a full stacktrace.

**Comment by emetsger** [comment]
Stacktrace:

> ERROR [Thread-12]: o.d.p.g.p.i.PackageGenerationPresenterImpl@360 2017-04-10 11:55:32,101 entry size '37580963840' is too big ( > 8589934591 ) 
java.lang.RuntimeException: entry size '37580963840' is too big ( > 8589934591 )
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumber(TarArchiveOutputStream.java:623) ~[commons-compress-1.9.jar:1.9]
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.failForBigNumbers(TarArchiveOutputStream.java:608) ~[commons-compress-1.9.jar:1.9]
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:286) ~[commons-compress-1.9.jar:1.9]
	at org.dataconservancy.packaging.tool.impl.generator.BagItPackageAssembler.addFilesToArchive(BagItPackageAssembler.java:691) ~[dcs-packaging-tool-impl-1.0.4-SNAPSHOT.jar:na]
	at org.dataconservancy.packaging.tool.impl.generator.BagItPackageAssembler.addFilesToArchive(BagItPackageAssembler.java:717) ~[dcs-packaging-tool-impl-1.0.4-SNAPSHOT.jar:na]
	at org.dataconservancy.packaging.tool.impl.generator.BagItPackageAssembler.addFilesToArchive(BagItPackageAssembler.java:717) ~[dcs-packaging-tool-impl-1.0.4-SNAPSHOT.jar:na]
	at org.dataconservancy.packaging.tool.impl.generator.BagItPackageAssembler.addFilesToArchive(BagItPackageAssembler.java:717) ~[dcs-packaging-tool-impl-1.0.4-SNAPSHOT.jar:na]
	at org.dataconservancy.packaging.tool.impl.generator.BagItPackageAssembler.archiveBag(BagItPackageAssembler.java:667) ~[dcs-packaging-tool-impl-1.0.4-SNAPSHOT.jar:na]
	at org.dataconservancy.packaging.tool.impl.generator.BagItPackageAssembler.assemblePackage(BagItPackageAssembler.java:525) ~[dcs-packaging-tool-impl-1.0.4-SNAPSHOT.jar:na]
	at org.dataconservancy.packaging.tool.impl.BOREMPackageGenerator.generatePackage(BOREMPackageGenerator.java:122) ~[dcs-packaging-tool-impl-1.0.4-SNAPSHOT.jar:na]
	at org.dataconservancy.packaging.tool.impl.BasicPackageGenerationService.generatePackage(BasicPackageGenerationService.java:77) ~[dcs-packaging-tool-impl-1.0.4-SNAPSHOT.jar:na]
	at org.dataconservancy.packaging.gui.presenter.impl.PackageGenerationPresenterImpl.generateAndSavePackage(PackageGenerationPresenterImpl.java:355) [classes/:na]
	at org.dataconservancy.packaging.gui.presenter.impl.PackageGenerationPresenterImpl.access$600(PackageGenerationPresenterImpl.java:70) [classes/:na]
	at org.dataconservancy.packaging.gui.presenter.impl.PackageGenerationPresenterImpl$BackgroundPackageService$BackgroundService$1.call(PackageGenerationPresenterImpl.java:751) [classes/:na]
	at org.dataconservancy.packaging.gui.presenter.impl.PackageGenerationPresenterImpl$BackgroundPackageService$BackgroundService$1.call(PackageGenerationPresenterImpl.java:737) [classes/:na]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) [jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_73]
	at javafx.concurrent.Service.lambda$null$492(Service.java:725) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_73]
	at javafx.concurrent.Service.lambda$executeTask$493(Service.java:724) [jfxrt.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_73]

**Comment by emetsger** [comment]
It appears that tar file entries are limited to ~8 GiB.

**Comment by emetsger** [comment]
Attempting to create a ZIP (instead of TAR) succeeds.

**Comment by birkland** [comment]
Can the tool use the POSIX tar format instead, which has unlimited file
size?

**Comment by emetsger** [comment]
Perhaps, I'm looking at what commons-compress does

**Comment by emetsger** [comment]
Looks like it can: https://commons.apache.org/proper/commons-compress/javadocs/api-1.10/org/apache/commons/compress/archivers/tar/TarArchiveOutputStream.html
